# Generated by Django 6.0.1 on 2026-01-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_topping_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
